import streamlit as st
from langchain_ollama import OllamaLLM
from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnableSequence
import time


llm = OllamaLLM(model="llama3.2")


prompt_template = PromptTemplate(
    input_variables=["skills", "domain", "experience"],
    template="""
You are an interview coach helping a student prepare for a job interview.

Here is the student's profile:
- Skills: {skills}
- Domain: {domain}
- Experience Level: {experience}

Based on this, give me:

1. TECHNICAL QUESTIONS - 5 technical questions relevant to their skills and domain
2. HR QUESTIONS - 3 common HR questions they should prepare for
3. CODING QUESTIONS - 2 coding problems they might face (just the problem statement, no solution)
4. MODEL ANSWERS - write short sample answers for the HR questions above
5. AREAS TO IMPROVE - list 3 to 4 things they should work on before the interview

Keep everything simple and practical. Write like you're a mentor talking to a student, not like a textbook.
"""
)

chain = prompt_template | llm


st.set_page_config(page_title="AI Interview Prep", layout="wide")

# sidebar
st.sidebar.title("AI Interview Prep")
theme = st.sidebar.selectbox("Theme", ["Dark", "Light"])
st.sidebar.markdown("---")
st.sidebar.markdown("### What this does")
st.sidebar.markdown("Fill in your profile and the AI will generate interview questions and tips just for you.")
st.sidebar.markdown("---")
st.sidebar.markdown("### Steps")
st.sidebar.markdown("1. Enter your skills and domain\n2. Pick experience level\n3. Hit Generate")
st.sidebar.warning("Practice the answers out loud, don't just read them.")

# theme
if theme == "Dark":
    st.markdown("<style>.stApp { background-color: #0E1117; color: white; }</style>", unsafe_allow_html=True)
else:
    st.markdown("<style>.stApp { background-color: #f9f9f9; color: black; }</style>", unsafe_allow_html=True)

# main
st.title("AI Interview Preparation Agent")
st.write("Enter your details and get a personalized interview prep sheet generated by AI.")
st.markdown("---")

col1, col2 = st.columns([2, 1])

with col1:
    skills = st.text_input("Your Skills", placeholder="Python, Machine Learning, SQL...")
    domain = st.text_input("Job Domain / Role", placeholder="Data Scientist, Web Developer, AI Engineer...")

with col2:
    experience = st.selectbox("Experience Level", ["Fresher", "6 months", "1 year", "2+ years"])

st.markdown("---")

if st.button("Generate Interview Prep"):

    if not skills.strip() or not domain.strip():
        st.warning("Please fill in your skills and domain first.")

    else:

        progress = st.progress(0)
        for i in range(100):
            time.sleep(0.01)
            progress.progress(i + 1)

        with st.spinner("AI is preparing your interview sheet..."):
            response = chain.invoke({
                "skills": skills,
                "domain": domain,
                "experience": experience
            })
            answer = chain.invoke({
                "skills": skills,
                "domain": domain,
                "experience": experience
            })

        st.success("Done!")
        st.markdown("---")
        st.subheader("Your Interview Prep Sheet")


        placeholder = st.empty()
        text = ""
        for char in answer:
            text += char
            placeholder.markdown(text)
            time.sleep(0.002)

        st.markdown("---")

